version: '3.8'

services:
# Source for Prometheus Docker Compose setup:
# prometheus.io/download/
  prometheus:
    image: prom/prometheus:v3.7.2
    container_name: prometheus
    restart: unless-stopped
    networks:
      - monitoring_net
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

# Source for Grafana Docker Compose setup:
# github.com/grafana/grafana/releases
  grafana:
    image: grafana/grafana:12.2.1
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - monitoring_net
    env_file: .env
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

networks:
  monitoring_net:
    external: true

volumes:
  prometheus-data:
  grafana-data:
