version: '3'
vars:
  SERVER_ALIAS: "ocs01"
  REMOTE_BASE_PATH: "~/var/ocs-server"
tasks:
  deploy:
    desc: "Deploys OCS Inventory service to the server"
    cmds:

      - rsync -avz --delete ./compose/ {{.SERVER_ALIAS}}:{{.REMOTE_BASE_PATH}}/ocs_inventory/
      - |
        ssh {{.SERVER_ALIAS}} << 'EOF'
        cd {{.REMOTE_BASE_PATH}}/ocs_inventory
        if [ -f "docker-compose.yml" ]; then
          docker-compose down && docker-compose up -d && echo "OCS Inventory restarted successfully."
        else
          echo "Error: docker-compose.yml not found in {{.REMOTE_BASE_PATH}}/ocs_inventory!"
        fi
        EOF
