"""auto_schema_update

Revision ID: 632ef22578b0
Revises: 
Create Date: 2026-03-29 13:11:23.095026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '632ef22578b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(length=10), nullable=False),
    sa.Column('device_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('compatibility_level', sa.Enum('bronze', 'silver', 'gold', name='compatibilitylevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hardware_device_id'), 'hardware', ['device_id'], unique=False)
    op.create_index(op.f('ix_hardware_id'), 'hardware', ['id'], unique=False)
    op.create_index(op.f('ix_hardware_vendor_id'), 'hardware', ['vendor_id'], unique=False)
    op.create_table('software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('compatibility_level', sa.Enum('bronze', 'silver', 'gold', name='compatibilitylevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_id'), 'software', ['id'], unique=False)
    op.create_index(op.f('ix_software_name'), 'software', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_software_name'), table_name='software')
    op.drop_index(op.f('ix_software_id'), table_name='software')
    op.drop_table('software')
    op.drop_index(op.f('ix_hardware_vendor_id'), table_name='hardware')
    op.drop_index(op.f('ix_hardware_id'), table_name='hardware')
    op.drop_index(op.f('ix_hardware_device_id'), table_name='hardware')
    op.drop_table('hardware')
    # ### end Alembic commands ###
